refactor: update zookeeper rock to charmed-zookeeper-rock
canonical/charmed-zookeeper-rock pull request #15
Opened 2023-03-31 15:05 UTC by marcoppenheimer

## Changes Made
##### `refactor: use rockcraft to build from snap instead of Dockerfile`

##### `refactor: use new image layout`
- `/bin/` for core files
- `/usr/lib` for Java
- `/etc/zookeeper` for config
- `/var/lib/zookeeper` for data
- `/var/log/zookeeper` for logs
- `/opt/zookeeper` for exporters and scripts

##### `cicd: update build/release CI`
- Publishes to GHCR now
- Only builds and releases

##### `chore: use java 17`

##### `temp/cicd: remove tests from ci`
- Will be added back after charm changes are applied

2023-03-31 15:07 UTC, marcoppenheimer commented on .github/workflows/publish.yaml
> +          docker push ghcr.io/canonical/charmed-zookeeper:${tag}
@taurus-forever I copied this from your changes in the `charmed-kafka-rock` PR

AFAIK, this will tag with `3.6.4-22.04_edge`. That's what we need? Not `3/edge` or similar?

2023-03-31 15:09 UTC, marcoppenheimer commented
@taurus-forever What's your recommendation for repo changes we should employ here?

`3/edge` core branch, rename repo to `charmed-zookeeper-rock`, add necessary API keys?
Or should the core branch be `3.6.4-22.04_edge`?

Agree with your suggestion to have a bare `main`, but will add that later.

2023-04-03 07:49 UTC, welpaolo approved these changes

2023-04-03 08:27 UTC, deusebio approved these changes
LGTM, but looping in @delgod that is @taurus-forever deputy this week

2023-04-03 08:27 UTC, deusebio commented on tox.ini
> +	base-name=ghcr.io/canonical/charmed-zookeeper:3.6.4-22.04_edge
**niptick** maybe we could use the variable version in the name, just to have a single point and prevent bugs

2023-04-03 09:24 UTC, delgod requested changes

2023-04-03 09:24 UTC, delgod commented on tox.ini
> +	base-name=ghcr.io/canonical/charmed-zookeeper:3.6.4-22.04_edge
I prefer to store the version only inside `rockcraft.yaml` without hardcoding here (`yq .version rockcraft.yaml` can help). see [comment below](https://github.com/canonical/zookeeper-rock/pull/15#discussion_r1155676048)
```suggestion
	base-name=ghcr.io/canonical/charmed-zookeeper
```

2023-04-03 09:24 UTC, delgod commented on tox.ini
> +	microk8s ctr image import charmed-zookeeper{env:version}_amd64.rock --base-name {env:base-name}
```suggestion
	bash -ec 'if ! [ -f charmed-zookeeper_$(yq .version rockcraft.yaml)_amd64.rock ]; then rockcraft pack; fi' {posargs}
	microk8s ctr image import charmed-zookeeper_$(yq .version rockcraft.yaml)_amd64.rock --base-name {env:base-name}:$(yq .version rockcraft.yaml):$(yq .version rockcraft.yaml)-$(yq .base rockcraft.yaml | cut -d : -f 2)_edge
```

2023-04-03 09:24 UTC, delgod commented on .github/workflows/publish.yaml
> +          docker push ghcr.io/canonical/charmed-zookeeper:${tag}
Yes, we tag with `3.6.4-22.04_edge` and promote to `3-edge` and after testing to `3-stable`.
it is needed to be able to pin concrete version of rock inside concrete revision of charm.

2023-04-03 09:24 UTC, delgod commented on rockcraft.yaml
> +      chown -R 1000:1000 opt/zookeeper
it is simpler create dirs ONE bash command (not two separate `mkdir` and `chown` commands)
```suggestion
      install -d -o 1000 -g 1000 -m 755 \
          opt/zookeeper \
          var/lib/zookeeper \
          var/log/zookeeper \
          etc/zookeeper
```

2023-04-03 15:47 UTC, delgod approved these changes

2023-04-03 15:47 UTC, delgod commented on rockcraft.yaml
> +      mkdir -p $CRAFT_PART_INSTALL/etc/zookeeper/
feel free to ignore: if you have `install -d` below, then maybe `mkdir` is not needed here

2023-04-03 15:50 UTC, merged